# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: MIT-0

class WidgetCmdMap
  # @public
  def self.new: () -> WidgetCmdMap

  # @public
  def run: () -> untyped
end
