#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

module RatatuiRuby
  module Tea
    # See RatatuiRuby::Tea::Runtime.run
    def self.run: [M, Msg] (
      model: M,
      view: ^(M model, RatatuiRuby::TUI tui) -> untyped,
      update: ^(Msg msg, M model) -> (M | [M, Cmd::execution?] | [M, Cmd::Quit] | [M, nil]),
      ?init: ^() -> Msg
    ) -> M
  end
end
